// <auto-generated />
namespace Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EstruturaInicial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EstruturaInicial));
        
        string IMigrationMetadata.Id
        {
            get { return "201708310249113_EstruturaInicial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
